# -*- coding: utf-8 -*-
"""
Created on Thu Oct 23 10:34:09 2014

@author: dlieviant
"""

ntList = ["Matt",
          "Mark",
          "Luke",
          "John",
          "Acts",
          "Rom",
          "1Cor",
          "2Cor",
          "Gal",
          "Eph",
          "Phil",
          "Col",
          "1Thess",
          "2Thess",
          "1Tim",
          "2Tim",
          "Titus",
          "Phlm",
          "Heb",
          "Jas",
          "1Pet",
          "2Pet",
          "1John",
          "2John",
          "3John",
          "Jude",
          "Rev"]

bookList = dict(GENESIS="Gen",
                EXODUS="Exod",
                LEVITICUS="Lev",
                NUMBERS="Num",
                DEUTERONOMY="Deut",
                JOSHUA="Josh",
                JUDGES="Judg",
                RUTH="Ruth",
                FIRSTSAMUEL="1Sam",
                SECONDSAMUEL="2Sam",
                FIRSTKINGS="1Kgs",
                SECONDKINGS="2Kgs",
                FIRSTCHRONICLES="1Chr",
                SECONDCHRONICLES="2Chr",
                EZRA="Ezra",
                NEHEMIAH="Neh",
                ESTHER="Esth",
                JOB="Job",
                PSALMS="Ps",
                PROVERBS="Prov",
                ECCLESIASTES="Eccl",
                SONGSOFSOLOMON="Song",
                ISAIAH="Isa",
                JEREMIAH="Jer",
                LAMENTATIONS="Lam",
                EZEKIEL="Ezek",
                DANIEL="Dan",
                HOSEA="Hos",
                JOEL="Joel",
                AMOS="Amos",
                OBADIAH="Obad",
                JONAH="Jonah",
                MICAH="Mic",
                NAHUM="Nah",
                HABAKKUK="Hab",
                ZEPHANIAH="Zeph",
                MALACHI="Mal",
                MATTHEW="Matt",
                MARK="Mark",
                LUKE="Luke",
                JOHN="John",
                ACTS="Acts",
                ROMANS="Rom",
                FIRSTCORINTHIANS="1Cor",
                SECONDCORINTHIANS="2Cor",
                GALATIANS="Gal",
                EPHESIANS="Eph",
                PHILIPPIANS="Phil",
                COLOSSIANS="Col",
                FIRSTTHESSALONIANS="1Thess",
                SECONDTHESSALONIANS="2Thess",
                FIRSTTIMOTHY="1Tim",
                SECONDTIMOTHY="2Tim",
                TITUS="Titus",
                PHILEMON="Phlm",
                HEBREWS="Heb",
                JAMES="Jas",
                FIRSTPETER="1Pet",
                SECONDPETER="2Pet",
                FIRSTJOHN="1John",
                SECONDJOHN="2John",
                THIRDJOHN="3John",
                JUDE="Jude",
                REVELATIONS="Rev")
                
                
                
                
                
                
                