# -*- coding: utf-8 -*-
"""
Created on Thu Oct 23 10:34:09 2014

@author: dlieviant
"""

ntList = ["Matt",
          "Mark",
          "Luke",
          "John",
          "Acts",
          "Rom",
          "1Cor",
          "2Cor",
          "Gal",
          "Eph",
          "Phil",
          "Col",
          "1Thess",
          "2Thess",
          "1Tim",
          "2Tim",
          "Titus",
          "Phlm",
          "Heb",
          "Jas",
          "1Pet",
          "2Pet",
          "1John",
          "2John",
          "3John",
          "Jude",
          "Rev"]

bookListEN = dict(GENESIS="Gen",
                EXODUS="Exod",
                LEVITICUS="Lev",
                NUMBERS="Num",
                DEUTERONOMY="Deut",
                JOSHUA="Josh",
                JUDGES="Judg",
                RUTH="Ruth",
                FIRSTSAMUEL="1Sam",
                SECONDSAMUEL="2Sam",
                FIRSTKINGS="1Kgs",
                SECONDKINGS="2Kgs",
                FIRSTCHRONICLES="1Chr",
                SECONDCHRONICLES="2Chr",
                EZRA="Ezra",
                NEHEMIAH="Neh",
                ESTHER="Esth",
                JOB="Job",
                PSALMS="Ps",
                PROVERBS="Prov",
                ECCLESIASTES="Eccl",
                SONGSOFSOLOMON="Song",
                ISAIAH="Isa",
                JEREMIAH="Jer",
                LAMENTATIONS="Lam",
                EZEKIEL="Ezek",
                DANIEL="Dan",
                HOSEA="Hos",
                JOEL="Joel",
                AMOS="Amos",
                OBADIAH="Obad",
                JONAH="Jonah",
                MICAH="Mic",
                NAHUM="Nah",
                HABAKKUK="Hab",
                ZEPHANIAH="Zeph",
                HAGGAI="Hag",
                ZECHARIAH="Zech",
                MALACHI="Mal",
                MATTHEW="Matt",
                MARK="Mark",
                LUKE="Luke",
                JOHN="John",
                ACTS="Acts",
                ROMANS="Rom",
                FIRSTCORINTHIANS="1Cor",
                SECONDCORINTHIANS="2Cor",
                GALATIANS="Gal",
                EPHESIANS="Eph",
                PHILIPPIANS="Phil",
                COLOSSIANS="Col",
                FIRSTTHESSALONIANS="1Thess",
                SECONDTHESSALONIANS="2Thess",
                FIRSTTIMOTHY="1Tim",
                SECONDTIMOTHY="2Tim",
                TITUS="Titus",
                PHILEMON="Phlm",
                HEBREWS="Heb",
                JAMES="Jas",
                FIRSTPETER="1Pet",
                SECONDPETER="2Pet",
                FIRSTJOHN="1John",
                SECONDJOHN="2John",
                THIRDJOHN="3John",
                JUDE="Jude",
                REVELATIONS="Rev")
                
bookListID = dict(KEJADIAN="Gen",
                  KELUARAN="Exod",
                  IMAMAT="Lev",
                  BILANGAN="Num",
                  ULANGAN="Deut",
                  YOSUA="Josh",
                  HAKIMHAKIM="Judg",
                  RUT="Ruth",
                  SATUSAMUEL="1Sam",
                  DUASAMUEL="2Sam",
                  SATURAJARAJA="1Kgs",
                  DUARAJARAJA="2Kgs",
                  SATUTAWARIKH="1Chr",
                  DUATAWARIKH="2Chr",
                  EZRA="Ezra",
                  NEHEMIAH="Neh",
                  ESTER="Esth",
                  AYUB="Job",
                  MAZMUR="Ps",
                  AMSAL="Prov",
                  PENGKHOTBAH="Eccl",
                  KIDUNGAGUNG="Song",
                  YESAYA="Isa",
                  YEREMIA="Jer",
                  RATAPAN="Lam",
                  YEHEZKIEL="Ezek",
                  DANIEL="Dan",
                  HOSEA="Hos",
                  YOEL="Joel",
                  AMOS="Amos",
                  OBAJA="Obad",
                  YUNUS="Jonah",
                  MIKHA="Mic",
                  NAHUM="Nah",
                  HABAKUK="Hab",
                  ZEFANYA="Zeph",
                  HAGAI="Hag",
                  ZAKHARIA="Zech",
                  MALEAKHI="Mal",
                  MATIUS="Matt",
                  MARKUS="Mark",
                  LUKAS="Luke",
                  YOHANES="John",
                  KISAHPARARASUL="Acts",
                  ROMA="Rom",
                  SATUKORINTUS="1Cor",
                  DUAKORINTUS="2Cor",
                  GALATIA="Gal",
                  EFESUS="Eph",
                  FILIPI="Phil",
                  KOLOSE="Col",
                  SATUTESALONIKA="1Thess",
                  DUATESALONIKA="2Thess",
                  SATUTIMOTIUS="1Tim",
                  DUATIMOTIUS="2Tim",
                  TITUS="Titus",
                  FILEMON="Phlm",
                  IBRANI="Heb",
                  YAKOBUS="Jas",
                  SATUPETRUS="1Pet",
                  DUAPETRUS="2Pet",
                  SATUYOHANES="1John",
                  DUAYOHANES="2John",
                  TIGAYOHANES="3John",
                  YUDAS="Jude",
                  WAHYU="Rev")                
                
utterances = dict(book="Please specify the book to read.",
                  chapter="Please choose the chapter.",
                  repeat="Cannot find chapter. Please repeat.",
                  pardon="Pardon?",
                  prompt="To cancel, say cancel. Otherwise, say continue.",
                  cancel="Cancelling...",
                  opening="Opening the Bible. Please wait.",
                  closing="Closing the Bible",
                  stop="Stopping reading.",
                  pause="Pausing reading.",
                  continuing="Continue reading.")                
                
                
                