# -*- coding: utf-8 -*-
"""
Created on Thu Oct 23 10:34:09 2014

@author: dlieviant
"""

ntList = ["Matt",
          "Mark",
          "Luke",
          "John",
          "Acts",
          "Rom",
          "1Cor",
          "2Cor",
          "Gal",
          "Eph",
          "Phil",
          "Col",
          "1Thess",
          "2Thess",
          "1Tim",
          "2Tim",
          "Titus",
          "Phlm",
          "Heb",
          "Jas",
          "1Pet",
          "2Pet",
          "1John",
          "2John",
          "3John",
          "Jude",
          "Rev"]

idListOT = dict(ENGLISH="ENGESVO2DA",
                INDONESIAN="INZNTVO2DA")
                
idListNT = dict(ENGLISH="ENGESVN2DA",
                INDONESIAN="INZNTVN2DA")

bookList = dict(GENESIS="Gen",
                EXODUS="Exod",
                LEVITICUS="Lev",
                NUMBERS="Num",
                DEUTERONOMY="Deut",
                JOSHUA="Josh",
                JUDGES="Judg",
                RUTH="Ruth",
                FIRSTSAMUEL="1Sam",
                SECONDSAMUEL="2Sam",
                FIRSTKINGS="1Kgs",
                SECONDKINGS="2Kgs",
                FIRSTCHRONICLES="1Chr",
                SECONDCHRONICLES="2Chr",
                EZRA="Ezra",
                NEHEMIAH="Neh",
                ESTHER="Esth",
                JOB="Job",
                PSALMS="Ps",
                PROVERBS="Prov",
                ECCLESIASTES="Eccl",
                SONGSOFSOLOMON="Song",
                ISAIAH="Isa",
                JEREMIAH="Jer",
                LAMENTATIONS="Lam",
                EZEKIEL="Ezek",
                DANIEL="Dan",
                HOSEA="Hos",
                JOEL="Joel",
                AMOS="Amos",
                OBADIAH="Obad",
                JONAH="Jonah",
                MICAH="Mic",
                NAHUM="Nah",
                HABAKKUK="Hab",
                ZEPHANIAH="Zeph",
                HAGGAI="Hag",
                ZECHARIAH="Zech",
                MALACHI="Mal",
                MATTHEW="Matt",
                MARK="Mark",
                LUKE="Luke",
                JOHN="John",
                ACTS="Acts",
                ROMANS="Rom",
                FIRSTCORINTHIANS="1Cor",
                SECONDCORINTHIANS="2Cor",
                GALATIANS="Gal",
                EPHESIANS="Eph",
                PHILIPPIANS="Phil",
                COLOSSIANS="Col",
                FIRSTTHESSALONIANS="1Thess",
                SECONDTHESSALONIANS="2Thess",
                FIRSTTIMOTHY="1Tim",
                SECONDTIMOTHY="2Tim",
                TITUS="Titus",
                PHILEMON="Phlm",
                HEBREWS="Heb",
                JAMES="Jas",
                FIRSTPETER="1Pet",
                SECONDPETER="2Pet",
                FIRSTJOHN="1John",
                SECONDJOHN="2John",
                THIRDJOHN="3John",
                JUDE="Jude",
                REVELATIONS="Rev")

nextList = dict(GENESIS="EXODUS",
                EXODUS="LEVITICUS",
                LEVITICUS="NUMBERS",
                NUMBERS="DEUTERONOMY",
                DEUTERONOMY="JOSHUA",
                JOSHUA="JUDGES",
                JUDGES="RUTH",
                RUTH="FIRSTSAMUEL",
                FIRSTSAMUEL="SECONDSAMUEL",
                SECONDSAMUEL="FIRSTKINGS",
                FIRSTKINGS="SECONDKINGS",
                SECONDKINGS="2FIRSTCHRONICLESKgs",
                FIRSTCHRONICLES="SECONDCHRONICLES",
                SECONDCHRONICLES="EZRA",
                EZRA="NEHEMIAH",
                NEHEMIAH="ESTHER",
                ESTHER="JOB",
                JOB="PSALMS",
                PSALMS="PROVERBS",
                PROVERBS="ECCLESIASTES",
                ECCLESIASTES="SONGSOFSOLOMON",
                SONGSOFSOLOMON="ISAIAH",
                ISAIAH="JEREMIAH",
                JEREMIAH="LAMENTATIONS",
                LAMENTATIONS="EZEKIEL",
                EZEKIEL="DANIEL",
                DANIEL="HOSEA",
                HOSEA="JOEL",
                JOEL="AMOS",
                AMOS="OBADIAH",
                OBADIAH="JONAH",
                JONAH="MICAH",
                MICAH="NAHUM",
                NAHUM="HABAKKUK",
                HABAKKUK="ZEPHANIAH",
                ZEPHANIAH="HAGGAI",
                HAGGAI="ZECHARIAH",
                ZECHARIAH="MALACHI",
                MALACHI="MATTHEW",
                MATTHEW="MARK",
                MARK="LUKE",
                LUKE="JOHN",
                JOHN="ACTS",
                ACTS="ROMANS",
                ROMANS="FIRSTCORINTHIANS",
                FIRSTCORINTHIANS="SECONDCORINTHIANS",
                SECONDCORINTHIANS="GALATIANS",
                GALATIANS="EPHESIANS",
                EPHESIANS="PHILIPPIANS",
                PHILIPPIANS="COLOSSIANS",
                COLOSSIANS="FIRSTTHESSALONIANS",
                FIRSTTHESSALONIANS="SECONDTHESSALONIANS",
                SECONDTHESSALONIANS="FIRSTTIMOTHY",
                FIRSTTIMOTHY="SECONDTIMOTHY",
                SECONDTIMOTHY="TITUS",
                TITUS="PHILEMON",
                PHILEMON="HEBREWS",
                HEBREWS="JAMES",
                JAMES="FIRSTPETER",
                FIRSTPETER="SECONDPETER",
                SECONDPETER="FIRSTJOHN",
                FIRSTJOHN="SECONDJOHN",
                SECONDJOHN="THIRDJOHN",
                THIRDJOHN="JUDE",
                JUDE="REVELATIONS",
                REVELATIONS="GENESIS")
                
utterances = dict(welcome="Welcome to Fig, the interactive bible.",
                  prompt="How can I be of service?",
                  book="Please specify the book to read.",
                  chapter="Please choose the chapter.",
                  repeat="Cannot find chapter. Please repeat.",
                  pardon="Pardon?",
                  confirm="To cancel, say cancel. Otherwise, say continue.",
                  cancel="Cancelling...",
                  opening="Opening the Bible. Please wait.",
                  closing="Closing the Bible",
                  stop="Stopping reading.",
                  pause="Pausing reading.",
                  continuing="Continue reading.",
                  nextchap="To continue to next chapter, say continue. Otherwise, say close.",
                  changelang="Please choose a language.",
                  end="Thank you for using Fig.")                
                
#dictList = dict(ENGLISH=["dictionary_bible.dic", "dictionary_playback.dic", "dictionary_num.dic"],
#                INDONESIAN=["dictionary_indo.dic", "dictionary_playindo.dic", "dictionary_numindo.dic"])                
                